<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2XgqjcL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2XgqjcL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2XgqjcL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2XgqjcL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2XgqjcL\App_KernelDevDebugContainer([
    'container.build_hash' => '2XgqjcL',
    'container.build_id' => '61b074ee',
    'container.build_time' => 1653947387,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2XgqjcL');
